site_name: Nefarius' Project Documentation
site_url: https://docs.nefarius.at
repo_url: https://github.com/nefarius/docs.nefarius.at
site_description: Projects devoted to USB input device emulation and game peripherals reverse engineering
copyright: >
  Copyright &copy; 2020 - 2023 <a href="https://github.com/nefarius" target="_blank" rel="noopener">Benjamin Höglinger-Stelzer</a> -
  <a href="#__consent">Change cookie settings</a>

theme:
  name: material
  favicon: images/favicon.png
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
  custom_dir: overrides

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/nefarius
    - icon: fontawesome/brands/discord
      link: https://discord.nefarius.at
    - icon: fontawesome/brands/mastodon
      link: https://fosstodon.org/@Nefarius
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
extra_css:
  - stylesheets/extra.css
  - stylesheets/toots.css
  - stylesheets/video.css
extra_javascript:
  - javascripts/main.js  

plugins:
  - search:
      lang: en
  - glightbox:
      touchNavigation: true
      loop: false
      effect: zoom
      slide_effect: slide
      width: 100%
      height: auto
      zoomable: true
      draggable: true
      auto_caption: false
      caption_position: bottom

markdown_extensions:
  - admonition:
  - attr_list:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.superfences:
  - pymdownx.keys:
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.details:
  - pymdownx.tilde:
  - pymdownx.magiclink:
      repo_url_shorthand: true
      social_url_shorthand: true
